# admin/config.yml

backend:
  name: github
  repo: DimonMaxx/my-site
  branch: main
  base_url: https://decap-proxy.macsimenkodima.workers.dev
  auth_endpoint: /auth

media_folder: 'assets/uploads'
public_folder: '/assets/uploads'

locale: 'ru'

collections:
  - name: 'news'
    label: 'Новости'
    label_singular: 'Новость'
    folder: '_content/news/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Дата', name: 'date', widget: 'datetime' }
      - { label: 'Текст', name: 'body', widget: 'markdown' }

  - name: 'programs'
    label: 'Программы'
    label_singular: 'Программа'
    folder: '_content/programs/'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }
      - { label: 'Описание', name: 'description', widget: 'text' }
      - { label: 'Версия', name: 'version', widget: 'string', required: false }
      - { label: 'Размер (МБ)', name: 'size', widget: 'number', required: false }
      - { label: 'Ссылка для скачивания', name: 'download_link', widget: 'string' }

  - name: 'books'
    label: 'Книги'
    label_singular: 'Книга'
    folder: '_content/books/'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }
      - { label: 'Автор', name: 'author', widget: 'string' }
      - { label: 'Описание', name: 'description', widget: 'text' }
      - { label: 'Формат', name: 'format', widget: 'string', default: 'PDF' }
      - { label: 'Ссылка для скачивания', name: 'download_link', widget: 'string' }

  - name: 'articles'
    label: 'Статьи'
    label_singular: 'Статья'
    folder: '_content/articles/'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Дата', name: 'date', widget: 'datetime' }
      - { label: 'Текст', name: 'body', widget: 'markdown' }

  - name: 'movies'
    label: 'Фильмы'
    label_singular: 'Фильм'
    folder: '_content/movies/'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }
      - { label: 'Год', name: 'year', widget: 'number' }
      - { label: 'Описание', name: 'description', widget: 'text' }
      - { label: 'Ссылка для скачивания', name: 'download_link', widget: 'string' }

  - name: 'misc'
    label: 'Разное'
    label_singular: 'Материал'
    folder: '_content/misc/'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }
      - { label: 'Описание', name: 'description', widget: 'text' }
      - { label: 'Ссылка для скачивания', name: 'download_link', widget: 'string' }
